### ISSUE TITLE
Failed to add dependencies while docker-compose build

### ISSUE THREAD

**Issue by c0mm4nd** [seed-labs/seed-emulator#156] opened 2023-08-26 15:05 UTC
When running A03-real-world (and other example with WebService), stuck on `RUN apt-get update && apt-get install -y --no-install-recommends nginx-light` and never exit:
```
 => => # Unpacking nginx-light (1.18.0-0ubuntu1.4) ...                                                                                                                            
 => => # Setting up nginx-common (1.18.0-0ubuntu1.4) ...                                                                                                                          
 => => # Setting up libnginx-mod-http-echo (1.18.0-0ubuntu1.4) ...                                                                                                                
 => => # Setting up nginx-light (1.18.0-0ubuntu1.4) ...                                                                                                                           
 => => # invoke-rc.d: could not determine current runlevel                                                                                                                        
 => => # invoke-rc.d: policy-rc.d denied execution of start.  
```

![image](https://github.com/seed-labs/seed-emulator/assets/12538215/b0a0636a-b448-4314-9b0e-54a892d887ac)

**Comment by kevin-w-du** [comment] 2023-08-26 20:25
I don't have this issue on my side. I am asking Kyungrok to do another test from a fresh-built VM. This might be an issue caused by your local environment.

**Comment by wonkr** [comment] 2023-08-26 21:50
@c0mm4nd 
I did a test from a fresh-build VM (Ubuntu 20.04) and have no issue on my side either. 
It seems that you are running a Docker on MAC OS. This might cause this issue. 
As this issue is not caused from our codes, I will close the issue.

**Closed by wonkr** 2023-08-26 21:50 UTC
